server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/rreciclagem}
spring.datasource.username=${DB_USER:rreciclagem}
spring.datasource.password=${DB_PASSWORD:rreciclagem123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET:trocar-por-um-segredo-forte-com-32-caracteres-no-minimo}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

logging.level.org.springframework.security=${LOG_LEVEL_SECURITY:INFO}
logging.level.br.com.fiap=${LOG_LEVEL_APP:INFO}
